name: Build BattleShip Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
      - name: Run PyInstaller
        run: |
          pyinstaller --onefile --name battleship cli.py &&
          cd dist/ &&
          zip battleship.zip battleship
      - uses: actions/upload-artifact@v3
        with:
          name: battleship
          path: dist/battleship.zip
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1
          release_name: Battleship v1
          body: |
            Python v3.7
            OS Linux
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/battleship.zip
          asset_name: battleship.zip
          asset_content_type: application/zip
